{% set name = "latex-rubber" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/latex-rubber-{{ version }}.tar.gz
  sha256: 47bbf8d6511f6d85f98baebbebb7cb1a58e9e6b1f92ff09fa6d8c08a683ea665

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - rubber
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/latex-rubber/rubber
  summary: an automated system for building LaTeX documents
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - HaoZeke
